[tool.poetry]
name = "hazm"
version = "0.12.1"
description = "Persian NLP Toolkit"
authors = ["Roshan <salam@roshan-ai.com>"]
maintainers = ["Roshan <salam@roshan-ai.com>"]
license = "MIT"
readme = "README.md"
include = ["data/*"]

classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Text Processing",
    "Natural Language :: Persian",
]

repository = "https://github.com/roshan-research/hazm/"
documentation = "https://roshan-ai.ir/hazm/docs/"
keywords = ["nlp", "persian nlp", "persian"]

[tool.poetry.urls]
"Demo" = "https://www.roshan-ai.ir/hazm/demo/"
"Changelog" = "https://github.com/roshan-research/hazm/releases/latest"
"Contribution" = "https://github.com/roshan-research/hazm/blob/master/CONTRIBUTION.md"
"Issues" = "https://github.com/roshan-research/hazm/issues"
"Join-us" = "https://www.roshan-ai.ir/join-us/"

[tool.poetry.dependencies]
python= ">=3.12, <3.14"
nltk="^3.9.0"
python-crfsuite="^0.9.12"
flashtext = "^2.7"
tqdm = "^4.67.3"
huggingface-hub = ">=0.25.0"

gensim = { version = "^4.4.0", optional = true }
numpy = { version = "^2.0.0", optional = true }
scikit-learn = { version = "^1.6.0", optional = true }
spacy = { version = "^3.8.0", optional = true }
spacy-transformers = { version = "^1.4.0", optional = true }
smart-open = { version = "^7.5.1", optional = true }

[tool.poetry.extras]
all = [
    "gensim", 
    "numpy", 
    "scikit-learn", 
    "spacy", 
    "spacy-transformers", 
    "smart-open"
]

[tool.poetry.group.docs.dependencies]
mkdocs="^1.6.1"
mkdocs-material="^9.7.6"
pymdown-extensions="^10.21.2"
mkdocs-glightbox="^0.5.2"
mkdocstrings = "^1.0.3"
mkdocstrings-python = "^2.0.3"
toml = "^0.10.2"
mkdocs-macros-plugin = "^1.5.0"

[tool.poetry.group.docs]
optional=true

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-xdist = {extras = ["psutil"], version = "^3.8.0"}
ruff = "^0.15.8"
pytest-cov = "^7.1.0"
pytest-sugar = "^1.1.1"
pyinstrument = "^5.1.2"
poethepoet = "^0.42.1"
numpy = "^2.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
fix = true
show-fixes = true
namespace-packages = ["hazm"]

[tool.ruff.lint]
extend-select = [
    "F", "E", "W", "C90", "I", "N", "D", "UP", "YTT", "ANN",
    "B", "A", "COM", "C4", "DTZ", "EM", "EXE", "ISC", "ICN", "G",
    "INP", "PIE", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID",
    "TCH", "INT", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "PLC",
    "PLE", "PLR", "PLW", "TRY", "NPY", "RUF"
]

ignore = [
    "RUF001", "RUF002", "RUF003",
    "D205", "E501", "F401", "TID252", "PLR0913",
    "ANN001", "ANN201", "ANN202",
    "PLR0912", "PLR0915", "PLR0911",
    "C901", "PLR2004", "E722", "PLW2901",
    "TRY002",
    "D100", "D101", "D102", "D103", "D104",
    "D105", "D106", "D107",
    "ANN401", "PLC0415"
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"data_utils.py" = ["ALL"]
"mkdocs_macros.py" = ["ALL"]
"wiki_extractor.py" = ["ALL"]
"__init__.py" = ["ALL"]

[tool.black]
target-version = ['py312']
preview = true

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning"]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

[tool.poe.tasks]
# poetry run poe test
# poetry run poe test hazm/normalizer.py
test = "pytest -n auto ${path}"

# poetry run poe lint
# poetry run poe lint -t hazm/normalizer.py
# poetry run poe lint -- --no-fix
[tool.poe.tasks.lint]
cmd  = "ruff check ${target_dir}" 
args = { target_dir = { options = ["--target", "-t"], default = "." }}
