from .BijankhanReader import BijankhanReader
from .DadeganReader import DadeganReader
from .DegarbayanReader import DegarbayanReader
from .HamshahriReader import HamshahriReader
from .MirasTextReader import MirasTextReader
from .PersicaReader import PersicaReader
from .PeykareReader import PeykareReader
from .QuranCorpusReader import QuranCorpusReader
from .SentiPersReader import SentiPersReader
from .TNewsReader import TNewsReader
from .TreebankReader import TreebankReader
from .VerbValencyReader import VerbValencyReader
from .WikipediaReader import WikipediaReader